If Not $CmdLine[0] = 1 Then
	MsgBox(4096,"Set the NVIDIA Display Profile Straightforwardly","Incorrect Command Line Paramaters!",10)
Else
	ShellExecute("nvcplui.exe","","c:\windows\system32")
	WinWait("NVIDIA Control Panel")
	WinActivate("NVIDIA Control Panel")
	Sleep(4000)
	Send("!p")
	Send("l")
	Send("!n")
	Sleep(2000)
	Send($CmdLine[1])
	Sleep(250)
	Send("!c!o!d!a!3")
	Sleep(250)
	Send("{ENTER}")
	WinWait("NVIDIA Control Panel")
	Sleep(250)
	Send("Y")
	WinWait("Apply Changes")
	Sleep(250)
	Send("Y")
	Sleep(250)
	Send("!{F4}")
EndIf
