swift -n Allison -m text -o "power_00.wav" "Oh no, my battery is dying!"
swift -n Allison -m text -o "power_10.wav" "Battery power level is now at 10 percent!"
swift -n Allison -m text -o "power_20.wav" "Battery power level is now at 20 percent!"
swift -n Allison -m text -o "power_30.wav" "Battery power level is now at 30 percent!"
swift -n Allison -m text -o "power_40.wav" "Battery power level is now at 40 percent!"
swift -n Allison -m text -o "power_50.wav" "Battery power level is now at 50 percent!"
swift -n Allison -m text -o "power_60.wav" "Battery power level is now at 60 percent!"
swift -n Allison -m text -o "power_70.wav" "Battery power level is now at 70 percent!"
swift -n Allison -m text -o "power_80.wav" "Battery power level is now at 80 percent!"
swift -n Allison -m text -o "power_90.wav" "Battery power level is now at 90 percent!"
swift -n Allison -m text -o "power_FF.wav" "My battery is now fully-charged!"
